/* eslint-disable @typescript-eslint/naming-convention */
import { type Actions, type Role, type Subjects } from "./interface";

export const rolePermissions: Record<Role, Array<{ action: Actions; subject: Subjects | Subjects[] }>> = {
  SUPER_ADMIN: [{ action: "manage", subject: "all" }],
  ADMIN: [
    { action: "read", subject: "dashboard" },
    { action: "read", subject: "folder" },
    { action: "read", subject: "position" },
    { action: "read", subject: "profile" },
    { action: "read", subject: "application" },
    { action: "read", subject: "company" },
    { action: "read", subject: "village" },
    { action: "read", subject: "printing" },
    { action: "read", subject: "renew" },
    { action: "read", subject: "printed" },
    { action: "read", subject: "nationality" },
    { action: "read", subject: "province" },
    { action: "read", subject: "district" },
    { action: "read", subject: "office" },
    { action: "read", subject: "add-blacklist-btn" },
    { action: "read", subject: "gallery" },
    { action: "read", subject: "take-photo" },
  ],
  FINANCE: [
    { action: "read", subject: "folder" },
    { action: "read", subject: "setting" },
    { action: "read", subject: "dashboard" },
    { action: "read", subject: "finance" },
    { action: "read", subject: "refund" },
    { action: "read", subject: "report" },
  ],
  POLICE_OFFICER: [
    { action: "read", subject: "setting" },
    { action: "read", subject: "folder" },
    { action: "read", subject: "dashboard" },
    { action: "read", subject: "position" },
    { action: "read", subject: "profile" },
    { action: "read", subject: "application" },
    { action: "read", subject: "company" },
    { action: "read", subject: "renew" },
    { action: "read", subject: "village" },
    { action: "read", subject: "gallery" },
    { action: "read", subject: "take-photo" },
    { action: "read", subject: "profile-report" },
  ],
  POLICE_COMMANDER: [
    { action: "read", subject: "dashboard" },
    { action: "read", subject: "folder" },
  ],
  POLICE_PRODUCTION: [
    { action: "read", subject: "dashboard" },
    { action: "read", subject: "printing" },
  ],
  VERSIFICATION_OFFICER: [
    { action: "read", subject: "scanner" },
    { action: "read", subject: "folder" },
    { action: "manage", subject: "create-folder" },
    // { action: "read", subject: "blacklist" },
  ],
};
